### ISSUE TITLE
Мне стоило учить линал

### ISSUE THREAD

**Issue by nokados** [cs-hse-projects/Oculus_VR_Furin_106#2]
Есть пушка. У нее известны координаты и поворот. За выстрел она может одновременно создать n пуль.
Чтобы пули вылетали красиво, я беру окружность радиуса 1 с центром в пушке и через равные дуги создаю пули.
То есть сдвиг я могу задать
Vector3(Mathf.Cos(angle), Mathf.Sin(angle));
и угол сдвигать на Math.PI*2 / bulletsByShot;
Но если просто к позиции пушки прибавить этот вектор, то в зависимости от поворота корабля случится подстава и пули полетят не оттуда.
Нужно как то прибавить его к плоскости или повернуть или что-то еще..

**Comment by pyos** [comment]
[Кватернионы-кватерниончики](http://ru.wikipedia.org/wiki/Кватернион). Смотри короч, поворот в 3д-пространстве на угол a вокруг оси u (`|u| = 1`, `u = x * i + y * j + z * k`) это кватернион `q = cos(x/2) + sin(x/2) * u`. Почему так? Потому что если взять функцию `F(x) = q * x * q^-1`, то она будет применять этот поворот к произвольному 3д-вектору.

Так вот. Тебе так-то нужно взять композицию двух поворотов: `q` - поворот корабля и `p` - поворот луча, по которому пойдет пуля. Сначала, чему равен `p`? Это поворот точно вокруг вертикальной оси (`k`) на угол `pi * 2 * n / bulletsByShot`. То есть `p = cos(pi * n / bulletsByShot) + sin(pi * n / bulletsByShot) * k` (где k - третья мнимая кватернионовая единица.)

Теперь композиция. `(f . g)(x) = q * (p * x * p^-1) * q^-1 = (q * p) * x * (p^-1 * q^-1) = (q * p) * x * (q * p)^-1`. А значит чтобы получить итоговый поворот, нужно просто перемножить два кватерниона.

Ну и чему равен `x`? А `x` это куда стреляла бы пушка, если бы пуля была одна, а корабль смотрел в нулевом направлении. То есть это вектор, по которому направлена пушка относительно корабля. Осталось только все посчитать.

**Comment by nokados** [comment]
Я ничего не понял, но спасибо Ден)
Пойду решать листок.
